/****************************************
 * Name:		Tyler Haddox
 * Username:	NA
 * Problem Set: PS3
 * Due Date: March 3, 2020
 ***************************************/

package aips4;

import java.io.File;
import java.util.ArrayList;
import javax.swing.JFileChooser;

public class AI_ps4_GUI extends javax.swing.JFrame {
    private final JFileChooser FileChooser = new JFileChooser();
    private AI_ps4_Tools myTools = new AI_ps4_Tools();
    
    public AI_ps4_GUI() {
        initComponents();
                FileChooser.setCurrentDirectory(new File("."));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        FileLabel = new javax.swing.JLabel();
        TextFieldFilePath = new javax.swing.JTextField();
        ButtonChooseFile = new javax.swing.JButton();
        Label_popCnt = new javax.swing.JLabel();
        TextField_popCnt = new javax.swing.JTextField();
        Label_maxItrCnt = new javax.swing.JLabel();
        TextField_maxItrCnt = new javax.swing.JTextField();
        Label_ksCapacity = new javax.swing.JLabel();
        TextField_ksCapacity = new javax.swing.JTextField();
        Label_mutPer = new javax.swing.JLabel();
        TextField_mutPer = new javax.swing.JTextField();
        Label_minFitScore = new javax.swing.JLabel();
        TextField_minFitScore = new javax.swing.JTextField();
        Button_runAlg = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextArea_results = new javax.swing.JTextArea();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        FileLabel1 = new javax.swing.JLabel();
        TextFieldFilePath1 = new javax.swing.JTextField();
        ButtonChooseFile1 = new javax.swing.JButton();
        Label_popCnt1 = new javax.swing.JLabel();
        TextField_popCnt1 = new javax.swing.JTextField();
        Label_maxItrCnt1 = new javax.swing.JLabel();
        TextField_maxItrCnt1 = new javax.swing.JTextField();
        Label_ksCapacity1 = new javax.swing.JLabel();
        TextField_ksCapacity1 = new javax.swing.JTextField();
        Label_mutPer1 = new javax.swing.JLabel();
        TextField_mutPer1 = new javax.swing.JTextField();
        Label_minFitScore1 = new javax.swing.JLabel();
        TextField_minFitScore1 = new javax.swing.JTextField();
        Button_runAlg1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TextArea_results1 = new javax.swing.JTextArea();
        Button_improved = new javax.swing.JButton();

        FileLabel.setText("File Path:");

        ButtonChooseFile.setText("Choose File");
        ButtonChooseFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonChooseFileActionPerformed(evt);
            }
        });

        Label_popCnt.setText("Population Count:");

        Label_maxItrCnt.setText("Max Iteration Count:");

        Label_ksCapacity.setText("Knapsack Capacity:");

        Label_mutPer.setText("Mutation Percent:");

        Label_minFitScore.setText("Minimum Fitness Score:");

        Button_runAlg.setText("Run Algorithm");
        Button_runAlg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_runAlgActionPerformed(evt);
            }
        });

        TextArea_results.setColumns(20);
        TextArea_results.setRows(5);
        jScrollPane1.setViewportView(TextArea_results);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Label_minFitScore)
                            .addComponent(Label_mutPer)
                            .addComponent(Label_ksCapacity)
                            .addComponent(Label_maxItrCnt)
                            .addComponent(Label_popCnt)
                            .addComponent(FileLabel))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(TextFieldFilePath, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ButtonChooseFile))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(TextField_minFitScore, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                                    .addComponent(TextField_mutPer, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TextField_ksCapacity, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TextField_popCnt, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TextField_maxItrCnt, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(80, 80, 80)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(Button_runAlg, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FileLabel)
                    .addComponent(TextFieldFilePath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonChooseFile))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Label_popCnt)
                            .addComponent(TextField_popCnt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Label_maxItrCnt)
                            .addComponent(TextField_maxItrCnt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Label_ksCapacity)
                            .addComponent(TextField_ksCapacity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Label_mutPer)
                            .addComponent(TextField_mutPer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Label_minFitScore)
                            .addComponent(TextField_minFitScore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)))
                .addComponent(Button_runAlg)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        FileLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        FileLabel1.setText("File Path:");

        TextFieldFilePath1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        TextFieldFilePath1.setText("Click 'Choose File' button to bring up file chooser.");

        ButtonChooseFile1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ButtonChooseFile1.setText("Choose File");
        ButtonChooseFile1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonChooseFile1ActionPerformed(evt);
            }
        });

        Label_popCnt1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Label_popCnt1.setText("Population Count:");

        TextField_popCnt1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        TextField_popCnt1.setText("20");

        Label_maxItrCnt1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Label_maxItrCnt1.setText("Max Iteration Count:");

        TextField_maxItrCnt1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        TextField_maxItrCnt1.setText("100");

        Label_ksCapacity1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Label_ksCapacity1.setText("Knapsack Capacity:");

        TextField_ksCapacity1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        TextField_ksCapacity1.setText("100");

        Label_mutPer1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Label_mutPer1.setText("Mutation Percent:");

        TextField_mutPer1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        TextField_mutPer1.setText("1");

        Label_minFitScore1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Label_minFitScore1.setText("Minimum Fitness Score:");

        TextField_minFitScore1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        TextField_minFitScore1.setText("300");

        Button_runAlg1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Button_runAlg1.setText("Run Algorithm");
        Button_runAlg1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_runAlg1ActionPerformed(evt);
            }
        });

        TextArea_results1.setColumns(20);
        TextArea_results1.setRows(5);
        jScrollPane2.setViewportView(TextArea_results1);

        Button_improved.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Button_improved.setText("Run Improved Alg");
        Button_improved.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_improvedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(FileLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TextFieldFilePath1)
                        .addGap(18, 18, 18)
                        .addComponent(ButtonChooseFile1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Label_minFitScore1)
                                    .addComponent(Label_mutPer1)
                                    .addComponent(Label_ksCapacity1)
                                    .addComponent(Label_maxItrCnt1)
                                    .addComponent(Label_popCnt1))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(TextField_minFitScore1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                                    .addComponent(TextField_mutPer1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TextField_ksCapacity1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TextField_popCnt1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TextField_maxItrCnt1, javax.swing.GroupLayout.Alignment.LEADING)))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Button_runAlg1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Button_improved, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 614, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonChooseFile1)
                    .addComponent(TextFieldFilePath1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FileLabel1))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Label_popCnt1)
                            .addComponent(TextField_popCnt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Label_maxItrCnt1)
                            .addComponent(TextField_maxItrCnt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Label_ksCapacity1)
                            .addComponent(TextField_ksCapacity1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Label_mutPer1)
                            .addComponent(TextField_mutPer1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Label_minFitScore1)
                            .addComponent(TextField_minFitScore1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(55, 55, 55)
                        .addComponent(Button_runAlg1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(Button_improved, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonChooseFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonChooseFileActionPerformed
        // ignore
    }//GEN-LAST:event_ButtonChooseFileActionPerformed

    private void Button_runAlgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_runAlgActionPerformed
        // ignore
    }//GEN-LAST:event_Button_runAlgActionPerformed

    private void Button_runAlg1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_runAlg1ActionPerformed

        myTools.resetAll();
        myTools.readFile(TextFieldFilePath1.getText());
        myTools.setKsCapacity(Float.parseFloat(TextField_ksCapacity1.getText()));
        myTools.setMaxItrCnt(Integer.parseInt(TextField_maxItrCnt1.getText()));
        myTools.setMinFitScore(Float.parseFloat(TextField_minFitScore1.getText()));
        myTools.setMutPer(Float.parseFloat(TextField_mutPer1.getText()));
        myTools.setPopCnt(Integer.parseInt(TextField_popCnt1.getText()));
        myTools.initialSelection();
        TextArea_results1.setText("");
        ArrayList<String> rstr = myTools.genetic();
        for(String str : rstr){
            TextArea_results1.append(str);
        }

    }//GEN-LAST:event_Button_runAlg1ActionPerformed

    private void ButtonChooseFile1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonChooseFile1ActionPerformed
        if (FileChooser.showOpenDialog(null) != JFileChooser.APPROVE_OPTION) {
            TextFieldFilePath1.setText("Click 'Choose File' button to bring up file chooser.");
        } else {
            TextFieldFilePath1.setText(FileChooser.getSelectedFile().getAbsolutePath());
        }
    }//GEN-LAST:event_ButtonChooseFile1ActionPerformed

    private void Button_improvedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_improvedActionPerformed
        
        myTools.resetAll();
        myTools.readFile(TextFieldFilePath1.getText());
        myTools.setKsCapacity(Float.parseFloat(TextField_ksCapacity1.getText()));
        myTools.setMaxItrCnt(Integer.parseInt(TextField_maxItrCnt1.getText()));
        myTools.setMinFitScore(Float.parseFloat(TextField_minFitScore1.getText()));
        myTools.setMutPer(Float.parseFloat(TextField_mutPer1.getText()));
        myTools.setPopCnt(Integer.parseInt(TextField_popCnt1.getText()));
        myTools.improvedInitialSelection();
        TextArea_results1.setText("");
        ArrayList<String> rstr = myTools.improvedGenetic();
        for(String str : rstr){
            TextArea_results1.append(str);
        }

    }//GEN-LAST:event_Button_improvedActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AI_ps4_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AI_ps4_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AI_ps4_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AI_ps4_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AI_ps4_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonChooseFile;
    private javax.swing.JButton ButtonChooseFile1;
    private javax.swing.JButton Button_improved;
    private javax.swing.JButton Button_runAlg;
    private javax.swing.JButton Button_runAlg1;
    private javax.swing.JLabel FileLabel;
    private javax.swing.JLabel FileLabel1;
    private javax.swing.JLabel Label_ksCapacity;
    private javax.swing.JLabel Label_ksCapacity1;
    private javax.swing.JLabel Label_maxItrCnt;
    private javax.swing.JLabel Label_maxItrCnt1;
    private javax.swing.JLabel Label_minFitScore;
    private javax.swing.JLabel Label_minFitScore1;
    private javax.swing.JLabel Label_mutPer;
    private javax.swing.JLabel Label_mutPer1;
    private javax.swing.JLabel Label_popCnt;
    private javax.swing.JLabel Label_popCnt1;
    private javax.swing.JTextArea TextArea_results;
    private javax.swing.JTextArea TextArea_results1;
    private javax.swing.JTextField TextFieldFilePath;
    private javax.swing.JTextField TextFieldFilePath1;
    private javax.swing.JTextField TextField_ksCapacity;
    private javax.swing.JTextField TextField_ksCapacity1;
    private javax.swing.JTextField TextField_maxItrCnt;
    private javax.swing.JTextField TextField_maxItrCnt1;
    private javax.swing.JTextField TextField_minFitScore;
    private javax.swing.JTextField TextField_minFitScore1;
    private javax.swing.JTextField TextField_mutPer;
    private javax.swing.JTextField TextField_mutPer1;
    private javax.swing.JTextField TextField_popCnt;
    private javax.swing.JTextField TextField_popCnt1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
